### ISSUE TITLE
NgramWordAnalyzer and PorterStemmer are not independent?

### ISSUE THREAD

**Issue by javadba** [meta-toolkit/metapy#2]
Based on feedback from CS410 instructor  Ismini Lourentzou I am reporting the following issue regarding the interaction of Ngrams and Stemmers in MeTA.

Briefly: should they not be ***_independent_** ?  In that case the  **order** should not matter.

However in MeTA the order does result in different results - consider:

    stemtok = metapy.analyzers.Porter2Filter(previousTokenizer)
    stemtok.set_content(doc.content())
    ng3ana = metapy.analyzers.NGramWordAnalyzer(3,stemtok)
    character_trigrams = ng3ana.analyze(doc)

The above yields slightly different results than the following:
    
      ng3ana = metapy.analyzers.NGramWordAnalyzer(3,stemtok)
      character_trigrams = ng3ana.analyze(doc)
      stemtok.set_content(doc.content())

Notice in the second case that the stemmer has occurred *after* the NGram. 

To better understand the intended concept of independence vs dependence -   consider a different pair of analyzers that *should* be dependent: the  stemmer and the  length analyzer. Swapping *those* analyzers that would definitely impact the result: e.g.  the stem of derivation and derived should be the same - maybe deriv ?  In that case if the length<=5 rule were applied before  the stemming then the word would disappear altogether: but after stemming it is retained.
 
But I do not perceive any fundamental reason why stemming and ngram generation should have any mutual effect /interactions: they should be independent,  no?  If they were independent then order should not matter.  But it does here. So then can we get some insight from the developer(s) why these two features actually do interact - and why?

**Comment by skystrife** [comment]
So I don't think fully understand your question, but I'm going to attempt to answer it anyway... please feel free to follow up if I've not answered the original question. It would help me immensely if you could have two separate, complete, snippets (as in, something I can run in a default `python` instance) demonstrating the different output vs what you expected it to output.

However...

I think this whole issue is basically confusion about the difference between a token stream and an analyzer. Think of it like this: the token stream, which starts with a tokenizer and follows it with a bunch of different filters, is just a way of obtaining a stream of tokens for a given document. The analyzer, on the other hand, is responsible for turning a stream of tokens obtained from a specific document into an actual document representation. Thus, it doesn't really make sense to say something like "give me trigrams and then run stemming", because at the point you've run the analyzer, you already have your document representation. The entire token stream has already been consumed and used to create a representation. Modifying that representation after the fact isn't the job of a filter: the filters only consume a token sequence to produce a modified token sequence. They don't know how to do anything to an existing document representation. You need to make sure that your token stream contains all of the filters you want it to have before you plug it into an analyzer for producing the document representation.

When you create an analyzer, it consumes a token stream. After the point you have created the analyzer, you should just use the analyzer. It doesn't really make sense to continue using the token stream at that point, since you've already used it to create an analyzer. You don't need to manually set the content of the token stream; the analyzer will do this for you. So if you want to create an analyzer on the token stream that is "run a tokenizer, then do stemming", then the first snippet you gave is the "correct" way to do it, but you should remove the call to `set_content` as the call to `analyze(doc)` will do that for you.

**Comment by javadba** [comment]
Hi - the *second* code snippet - the one with the 

  stemtok.set_content(doc.content())

*after* the ngram analyzer is the one marked as *correct* by the instructors of CS410. 

It seems from your comments above that the first coding snippet were more along the lines of the expected usage. But once again - the first code snippet was marked incorrect.

Resolution of the above may require discussion with the creators of the MP1 from CS410.

Afa working code snippets: I did not post them here because they could be copied for use by other students .  Please contact me offline to get access to the full snippets - which are in my gitlab repo.

sboesch2 at illinois.edu

**Comment by javadba** [comment]
Hi - what are the further thoughts on having this  be addressed?  The Instructor Ismina had confirmed this as a potential issue.

**Comment by skystrife** [comment]
This should be fixed in 0.2.8. Please upgrade with `pip install --upgrade metapy`.

I still maintain that the example usage here is incorrect. You should not need to set content on token streams passed to analyzers as the analyzer itself will call `set_content(doc.content())` on its own. The bug here was that `ICUTokenizer` did not properly clear any remaining internally buffered content when `set_content()` is called. This resulted in the analyzer seeing extra words that it shouldn't have, but only when constructed with a "dirty" tokenizer (one that has content already set on it).

**Comment by javadba** [comment]
Thx Chase. I will update our slack thread in the course as well.
